apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cm.name }}
  namespace: {{ .Values.namespace }}
data:
  webServerPort: "{{ .Values.cm.webServerPort }}"
  appServerPort: "{{ .Values.cm.appServerPort }}"
  dictFileURL: "{{ .Values.cm.dictFileURL }}"
