apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.web.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wolper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wolper.webSelectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wolper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.app.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wolper.appSelectorLabels" . | nindent 4 }}