name: Helm

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - '**.png'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - '**.png'
env:
  HELM_TEST_DIR: helm_test

jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    
    - name: Setup helm test
      run: make setup -C $HELM_TEST_DIR

    - name: Run helm test
      run: make test -C $HELM_TEST_DIR

    - name: Tear down helm test
      run: make clean -C $HELM_TEST_DIR
