name: Main

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - '**.png'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - '**.png'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Test
      run: make image